name: scivision
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - jupyter
  - pip
  - pip:
    - -r requirements.txt
    - git+https://github.com/ots22/intake-xarray@feature/exif
    - scivision