name: Check catalogs
on: push
  
jobs:
  check-catalogs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: automatic-scivision-checks
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Scivision
        run: pip install -e .
      - name: Check data catalog
        run: python ./dev/check_datasets.py
      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: check-datasets-report
          path: check_datasets.csv
